default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Beta track"
  lane :beta do
      # Grab the latest build number from the Play Store
      previous_build_number = google_play_track_version_codes(
        track: "internal",
        json_key: "/Users/belgamo/Desktop/play-store-credentials.json"
      )[0]

      # Increment the build number
      increment_version_code(
        gradle_file_path: "#{Dir.pwd}/../android/app/build.gradle",
        version_code: previous_build_number + 1
      )

      gradle(task: 'clean', project_dir: './android')
  
      # Build a release version of the app
      gradle(task: 'bundle', project_dir: "android", build_type: 'Release', properties: {
        "android.injected.signing.store.file" => "/Users/belgamo/Desktop/animavita-upload-key/animavita-upload-key.keystore",
        "android.injected.signing.store.password" => ENV["ANDROID_SIGNING_KEY_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_SIGNING_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_SIGNING_KEY_PASSWORD"]
      })

      # Upload the app to the Play Store
      upload_to_play_store(
        track: "internal",
        release_status: 'draft',
        json_key: "/Users/belgamo/Desktop/play-store-credentials.json"
      )
  end
end