name: Fly Staging Deploy - Backend

on:
  push:
    branches:
      - v2
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy --config ./apps/backend/fly.staging.toml --dockerfile ./apps/backend/Dockerfile
