name: Animavita Expo Tests

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/test-expo.yml'
      - 'packages/expo/**'
      - 'packages/ui/**'
      - 'packages/eslint/**'
      - 'packages/babel/**'
      - 'packages/theme/**'
    branches-ignore:
      - 'master'

jobs:
  test-expo:
    name: Expo Tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message , '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache dir
        id: get-yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn.lock
        id: yarn-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.get-yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: |
          yarn config set unsafe-disable-integrity-migration true -g
          yarn install --frozen-lockfile --production=false --non-interactive --cache-folder $(yarn cache dir)
      - name: Relay
        run: |
          yarn relay
          cp ./packages/relay/environment.example.ts ./packages/relay/environment.ts
      - name: Test Expo
        run: |
          yarn expo:test --ci --maxWorkers=2 --coverage --reporters=jest-junit --forceExit
        env:
          JEST_SUITE_NAME: 'Animavita Expo Tests'
          JEST_JUNIT_OUTPUT_DIR: './reports'
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
